# Generated by Django 2.2.18 on 2021-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('ag', models.CharField(max_length=100, verbose_name='Agência')),
                ('cc', models.CharField(max_length=100, verbose_name='C/C')),
                ('gerente', models.CharField(max_length=100, verbose_name='Gerente')),
                ('contato', models.CharField(max_length=100, verbose_name='Contato')),
                ('tel', models.CharField(max_length=100, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
    ]
