# Generated by Django 2.2.18 on 2021-02-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subconta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subconta', models.CharField(max_length=100, verbose_name='Subconta')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.Conta')),
            ],
            options={
                'ordering': ['subconta'],
            },
        ),
    ]
